#!/bin/sh
#Single line script to check number of connections on Port 80
#By Anidnya Roy
watch "netstat -an |grep :80 | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' | sort | uniq -c | wc -l"
